/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tutoriasacademi.IGU;

/**
 *
 * @author jeffersonparedespretel
 */
public class PortalAlumno extends javax.swing.JFrame {

    /**
     * Creates new form PortalAlumno
     */
    public PortalAlumno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DatosPersonaAlumno = new javax.swing.JFrame();
        jLabel237 = new javax.swing.JLabel();
        btnEditarAlumno = new javax.swing.JButton();
        jScrollPane20 = new javax.swing.JScrollPane();
        txtAreaDescripcionAlumno = new javax.swing.JTextArea();
        btnGuardarAlumno = new javax.swing.JButton();
        btnAtrasAlumno = new javax.swing.JButton();
        jDateChooser20 = new com.toedter.calendar.JDateChooser();
        jComboBox37 = new javax.swing.JComboBox<>();
        jLabel238 = new javax.swing.JLabel();
        txtCorreoAlumno = new javax.swing.JTextField();
        txtNacionalidadAlumno = new javax.swing.JTextField();
        txtClaveAlumno = new javax.swing.JTextField();
        jLabel240 = new javax.swing.JLabel();
        jLabel244 = new javax.swing.JLabel();
        jLabel247 = new javax.swing.JLabel();
        jLabel248 = new javax.swing.JLabel();
        jLabel249 = new javax.swing.JLabel();
        jLabel250 = new javax.swing.JLabel();
        txtNombreAlumo = new javax.swing.JTextField();
        txtApellidoAlumno = new javax.swing.JTextField();
        txtUsuarioAlumno = new javax.swing.JTextField();
        jLabel251 = new javax.swing.JLabel();
        jLabel252 = new javax.swing.JLabel();
        TutoriasPasadas = new javax.swing.JFrame();
        jLabel236 = new javax.swing.JLabel();
        jLabel239 = new javax.swing.JLabel();
        jScrollPane19 = new javax.swing.JScrollPane();
        jTable19 = new javax.swing.JTable();
        PedirTutoria = new javax.swing.JFrame();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        Tutoria = new javax.swing.JFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel235 = new javax.swing.JLabel();
        jButton76 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuTutorias = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuPerfil = new javax.swing.JMenu();
        jMenuItemDatosAlum = new javax.swing.JMenuItem();
        jMenuItemTutoriasPasa = new javax.swing.JMenuItem();

        jLabel237.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel237.setText("Nombre:");

        btnEditarAlumno.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnEditarAlumno.setText("Editar");
        btnEditarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarAlumnoActionPerformed(evt);
            }
        });

        txtAreaDescripcionAlumno.setColumns(20);
        txtAreaDescripcionAlumno.setRows(5);
        jScrollPane20.setViewportView(txtAreaDescripcionAlumno);

        btnGuardarAlumno.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnGuardarAlumno.setText("Guardar");

        btnAtrasAlumno.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnAtrasAlumno.setText("Atras");

        jDateChooser20.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N

        jComboBox37.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jComboBox37.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hombre", "Mujer", "Indeterminado" }));

        jLabel238.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel238.setText("Fecha de Nacimiento:");

        txtCorreoAlumno.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N

        txtNacionalidadAlumno.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N

        txtClaveAlumno.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N

        jLabel240.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel240.setText("Usuario");

        jLabel244.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel244.setText("Clave:");

        jLabel247.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel247.setText("Apellido:");

        jLabel248.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel248.setText("Datos Personales del Alumno:");

        jLabel249.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel249.setText("Genero:");

        jLabel250.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel250.setText("Nacionalidad:");

        txtNombreAlumo.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N

        txtApellidoAlumno.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        txtApellidoAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoAlumnoActionPerformed(evt);
            }
        });

        txtUsuarioAlumno.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N

        jLabel251.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel251.setText("Correo Electronico:");

        jLabel252.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel252.setText("Descripcion:");

        javax.swing.GroupLayout DatosPersonaAlumnoLayout = new javax.swing.GroupLayout(DatosPersonaAlumno.getContentPane());
        DatosPersonaAlumno.getContentPane().setLayout(DatosPersonaAlumnoLayout);
        DatosPersonaAlumnoLayout.setHorizontalGroup(
            DatosPersonaAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatosPersonaAlumnoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(DatosPersonaAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel248)
                    .addGroup(DatosPersonaAlumnoLayout.createSequentialGroup()
                        .addGroup(DatosPersonaAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel247)
                            .addComponent(jLabel251)
                            .addComponent(jLabel237)
                            .addComponent(jLabel238)
                            .addComponent(jLabel250)
                            .addComponent(jLabel252))
                        .addGap(18, 18, 18)
                        .addGroup(DatosPersonaAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(DatosPersonaAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DatosPersonaAlumnoLayout.createSequentialGroup()
                                    .addComponent(txtNacionalidadAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(167, 167, 167))
                                .addComponent(jDateChooser20, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(DatosPersonaAlumnoLayout.createSequentialGroup()
                                .addGroup(DatosPersonaAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(DatosPersonaAlumnoLayout.createSequentialGroup()
                                        .addGroup(DatosPersonaAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtNombreAlumo, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtApellidoAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(163, 163, 163)
                                        .addGroup(DatosPersonaAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel244)
                                            .addComponent(jLabel240)))
                                    .addComponent(jLabel249))
                                .addGap(11, 11, 11)
                                .addGroup(DatosPersonaAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtUsuarioAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                                    .addComponent(txtClaveAlumno)
                                    .addComponent(jComboBox37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txtCorreoAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DatosPersonaAlumnoLayout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(btnEditarAlumno)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnGuardarAlumno)
                                .addGap(84, 84, 84)
                                .addComponent(btnAtrasAlumno)
                                .addGap(144, 144, 144))
                            .addComponent(jScrollPane20))))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        DatosPersonaAlumnoLayout.setVerticalGroup(
            DatosPersonaAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatosPersonaAlumnoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel248, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(DatosPersonaAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel237)
                    .addComponent(txtNombreAlumo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel240)
                    .addComponent(txtUsuarioAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DatosPersonaAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel247, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellidoAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel244)
                    .addComponent(txtClaveAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DatosPersonaAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel251)
                    .addComponent(txtCorreoAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel249)
                    .addComponent(jComboBox37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DatosPersonaAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel250)
                    .addComponent(txtNacionalidadAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DatosPersonaAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(DatosPersonaAlumnoLayout.createSequentialGroup()
                        .addComponent(jLabel238)
                        .addGap(24, 24, 24))
                    .addGroup(DatosPersonaAlumnoLayout.createSequentialGroup()
                        .addComponent(jDateChooser20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)))
                .addGroup(DatosPersonaAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel252)
                    .addComponent(jScrollPane20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(DatosPersonaAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditarAlumno)
                    .addComponent(btnGuardarAlumno)
                    .addComponent(btnAtrasAlumno))
                .addGap(56, 56, 56))
        );

        jLabel236.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel236.setText("En este apartado podras revisar toda la infromacon de las tutorias en las que participaste ");

        jLabel239.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel239.setText("Tutorias Pasadas del Alumno:");

        jTable19.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane19.setViewportView(jTable19);

        javax.swing.GroupLayout TutoriasPasadasLayout = new javax.swing.GroupLayout(TutoriasPasadas.getContentPane());
        TutoriasPasadas.getContentPane().setLayout(TutoriasPasadasLayout);
        TutoriasPasadasLayout.setHorizontalGroup(
            TutoriasPasadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TutoriasPasadasLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(jLabel236)
                .addGap(19, 19, 19))
            .addGroup(TutoriasPasadasLayout.createSequentialGroup()
                .addGroup(TutoriasPasadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TutoriasPasadasLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel239))
                    .addGroup(TutoriasPasadasLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane19, javax.swing.GroupLayout.PREFERRED_SIZE, 692, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TutoriasPasadasLayout.setVerticalGroup(
            TutoriasPasadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TutoriasPasadasLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel239)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel236)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel8.setText("Pedir tutorias academicas");

        jLabel9.setText("Ingresa el Horario que deseas");

        jLabel10.setText("Fecha:");

        jLabel11.setText("Hora de inicio:");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Profesor", "Material de Estudio", "Curso", "Tema", "Fecha", "Hora Inicio", "Hora fin", "Costo por Hora"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jLabel12.setText("Hora de Finalizacion:");

        jLabel13.setText("Buscar:");

        jButton4.setText("Seleccionar");

        jButton5.setText("Realizar pago");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Salir");

        javax.swing.GroupLayout PedirTutoriaLayout = new javax.swing.GroupLayout(PedirTutoria.getContentPane());
        PedirTutoria.getContentPane().setLayout(PedirTutoriaLayout);
        PedirTutoriaLayout.setHorizontalGroup(
            PedirTutoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PedirTutoriaLayout.createSequentialGroup()
                .addGroup(PedirTutoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PedirTutoriaLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(PedirTutoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PedirTutoriaLayout.createSequentialGroup()
                                .addGroup(PedirTutoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jButton5))
                                .addGroup(PedirTutoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PedirTutoriaLayout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addGroup(PedirTutoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jTextField3)
                                            .addComponent(jTextField4)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PedirTutoriaLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                                        .addComponent(jButton6)
                                        .addGap(68, 68, 68))))
                            .addComponent(jLabel9)))
                    .addGroup(PedirTutoriaLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(PedirTutoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PedirTutoriaLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 713, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
            .addGroup(PedirTutoriaLayout.createSequentialGroup()
                .addGroup(PedirTutoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PedirTutoriaLayout.createSequentialGroup()
                        .addGap(494, 494, 494)
                        .addComponent(jLabel2))
                    .addGroup(PedirTutoriaLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel8)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PedirTutoriaLayout.setVerticalGroup(
            PedirTutoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PedirTutoriaLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGroup(PedirTutoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PedirTutoriaLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(PedirTutoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel9)
                        .addGap(30, 30, 30)
                        .addGroup(PedirTutoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PedirTutoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PedirTutoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(PedirTutoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton5)
                            .addComponent(jButton6)))
                    .addGroup(PedirTutoriaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout TutoriaLayout = new javax.swing.GroupLayout(Tutoria.getContentPane());
        Tutoria.getContentPane().setLayout(TutoriaLayout);
        TutoriaLayout.setHorizontalGroup(
            TutoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        TutoriaLayout.setVerticalGroup(
            TutoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Pago");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Confirar Pago");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Buscar Docente");

        jButton3.setText("Pago");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel3.setText("Para seguir se necesita de un:");

        jLabel7.setText("Buscar Docente");

        jLabel5.setText("jLabel5");

        jLabel6.setText("Pedir Tutorias:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel235.setBackground(new java.awt.Color(51, 102, 255));
        jLabel235.setFont(new java.awt.Font("Helvetica Neue", 0, 48)); // NOI18N
        jLabel235.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel235.setText("Bienvenido Estudiante");

        jButton76.setBackground(new java.awt.Color(255, 0, 51));
        jButton76.setForeground(new java.awt.Color(255, 255, 255));
        jButton76.setText("Salir");

        jDesktopPane1.setLayer(jLabel235, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton76, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel235, javax.swing.GroupLayout.DEFAULT_SIZE, 776, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton76)
                .addGap(36, 36, 36))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel235, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addComponent(jButton76)
                .addGap(27, 27, 27))
        );

        jMenuTutorias.setText("Tutorias");

        jMenuItem3.setText("Pedir Tutorias");
        jMenuTutorias.add(jMenuItem3);

        jMenuItem4.setText("Tutorias");
        jMenuTutorias.add(jMenuItem4);

        jMenuBar1.add(jMenuTutorias);

        jMenuPerfil.setBackground(new java.awt.Color(102, 255, 102));
        jMenuPerfil.setText("Perfil");

        jMenuItemDatosAlum.setText("Datos Personales");
        jMenuPerfil.add(jMenuItemDatosAlum);

        jMenuItemTutoriasPasa.setText("Tutorias Pasadas");
        jMenuItemTutoriasPasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTutoriasPasaActionPerformed(evt);
            }
        });
        jMenuPerfil.add(jMenuItemTutoriasPasa);

        jMenuBar1.add(jMenuPerfil);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarAlumnoActionPerformed

    private void txtApellidoAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoAlumnoActionPerformed

    private void jMenuItemTutoriasPasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTutoriasPasaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemTutoriasPasaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame DatosPersonaAlumno;
    private javax.swing.JFrame PedirTutoria;
    private javax.swing.JFrame Tutoria;
    private javax.swing.JFrame TutoriasPasadas;
    private javax.swing.JButton btnAtrasAlumno;
    private javax.swing.JButton btnEditarAlumno;
    private javax.swing.JButton btnGuardarAlumno;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton76;
    private javax.swing.JComboBox<String> jComboBox37;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser20;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel235;
    private javax.swing.JLabel jLabel236;
    private javax.swing.JLabel jLabel237;
    private javax.swing.JLabel jLabel238;
    private javax.swing.JLabel jLabel239;
    private javax.swing.JLabel jLabel240;
    private javax.swing.JLabel jLabel244;
    private javax.swing.JLabel jLabel247;
    private javax.swing.JLabel jLabel248;
    private javax.swing.JLabel jLabel249;
    private javax.swing.JLabel jLabel250;
    private javax.swing.JLabel jLabel251;
    private javax.swing.JLabel jLabel252;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItemDatosAlum;
    private javax.swing.JMenuItem jMenuItemTutoriasPasa;
    private javax.swing.JMenu jMenuPerfil;
    private javax.swing.JMenu jMenuTutorias;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane19;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane20;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable19;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField txtApellidoAlumno;
    private javax.swing.JTextArea txtAreaDescripcionAlumno;
    private javax.swing.JTextField txtClaveAlumno;
    private javax.swing.JTextField txtCorreoAlumno;
    private javax.swing.JTextField txtNacionalidadAlumno;
    private javax.swing.JTextField txtNombreAlumo;
    private javax.swing.JTextField txtUsuarioAlumno;
    // End of variables declaration//GEN-END:variables
}
